# Deploy to Non Prod env when PR created
name: Non Prod

# Controls when the action will run. 
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
concurrency: non-prod
env:
  AWS_ACCESS_KEY: ${{ secrets.TEST_SECRET }}
jobs:
  print_aws_access_key:
    steps:
      - run: |
        echo ${{ secrets.ENV_PRODUCTION_FILE }}


