# Deploy to Prod env when PR created
name: Prod

# Controls when the action will run. 
on:
  push:
    branches:
      - main
concurrency: prod
env:
  AWS_ACCESS_KEY: ${{ secrets.TEST_SECRET }}
jobs:
  print_aws_access_key:
    runs-on: ubuntu-latest
    steps:
      - name: test echo variable
        uses: actions/checkout@v3
      - run: |
          pip install awscli
